### ISSUE TITLE
npm install does not work on a mac

### ISSUE THREAD

**Issue by tofutim** [larscom/ng-chrome-extension#18]
Probably it is because it is mac, but for what it is worth:

```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/@larscom/ng-chrome-extension/node_modules/nodegit
npm ERR! command failed
npm ERR! command sh -c node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! [nodegit] Running pre-install script
npm ERR! [nodegit] Running install script
npm ERR! SOLINK_MODULE(target) Release/acquireOpenSSL.node
npm ERR! ACTION binding_gyp_configureLibssh2_target_configure .
npm ERR! [nodegit] Configuring libssh2.
npm ERR! SOLINK_MODULE(target) Release/configureLibssh2.node
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/allocators/stdalloc.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/commit.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/alloc.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/annotated_commit.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/apply.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/attr_file.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/attr.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/attrcache.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/blame_git.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/blame.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/blob.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/branch.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/buf_text.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/buffer.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/cache.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/checkout.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/cherrypick.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/clone.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/commit_list.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_cache.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_entries.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_file.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_mem.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_parse.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config_snapshot.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/config.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/crlf.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/date.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/delta.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_driver.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_file.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_generate.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_parse.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_print.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_stats.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_tform.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff_xdiff.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/diff.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/errors.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/fetch.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/fetchhead.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/filebuf.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/futils.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/filter.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/global.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/graph.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/hash.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/hash/sha1/sha1dc/sha1.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/hash/sha1/sha1dc/ubc_check.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/hash/sha1/collisiondetect.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/hashsig.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/ident.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/idxmap.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/ignore.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/index.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/indexer.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/iterator.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/mailmap.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/merge_driver.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/merge_file.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/merge.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/message.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/mwindow.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/net.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/netops.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/notes.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/object_api.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/object.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/odb_loose.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/odb_mempack.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/odb_pack.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/odb.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/offmap.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/oid.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/oidarray.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/oidmap.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/mbedtls.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/openssl.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/registry.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pack-objects.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pack.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/parse.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/patch_generate.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/patch_parse.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/patch.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/path.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pathspec.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pool.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/posix.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pqueue.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/proxy.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/push.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/reader.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/rebase.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/refdb_fs.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/refdb.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/reflog.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/refs.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/refspec.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/regexp.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/remote.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/repository.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/reset.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/revert.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/revparse.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/revwalk.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/settings.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/sha1_lookup.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/signature.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/socket.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/sortedcache.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/stash.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/status.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/strmap.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/submodule.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/sysdir.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/tag.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/thread-utils.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/trace.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/trailer.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transaction.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transport.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/cred_helpers.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/cred.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/git.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/local.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/smart_pkt.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/smart_protocol.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/smart.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/ssh.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/tree-cache.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/tree.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/tsort.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/util.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/varint.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/vector.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/wildmatch.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/worktree.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xdiffi.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xemit.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xhistogram.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xmerge.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xpatience.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xprepare.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/xdiff/xutils.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/zstream.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/stransport.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/http.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/auth.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/auth_negotiate.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/transports/auth_ntlm.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/streams/tls.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/unix/map.o
npm ERR! CC(target) Release/obj.target/libgit2/vendor/libgit2/src/unix/realpath.o
npm ERR! LIBTOOL-STATIC Release/git2.a
npm ERR! CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/adler32.o
npm ERR! CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/crc32.o
npm ERR! CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/deflate.o
npm ERR! CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/inffast.o
npm ERR! CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/inflate.o
npm ERR! CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/inftrees.o
npm ERR! CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/trees.o
npm ERR! CC(target) Release/obj.target/zlib/vendor/libgit2/deps/zlib/zutil.o
npm ERR! LIBTOOL-STATIC Release/zlib.a
npm ERR! CC(target) Release/obj.target/http_parser/vendor/http_parser/http_parser.o
npm ERR! LIBTOOL-STATIC Release/http_parser.a
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/agent.o
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/bcrypt_pbkdf.o
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/blowfish.o
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/crypt.o
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/keepalive.o
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/libgcrypt.o
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/openssl.o
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/publickey.o
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/sftp.o
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/version.o
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/channel.o
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/global.o
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/kex.o
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/mac.o
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/packet.o
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/scp.o
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/transport.o
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/comp.o
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/hostkey.o
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/knownhost.o
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/misc.o
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/pem.o
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/session.o
npm ERR! CC(target) Release/obj.target/libssh2/vendor/libssh2/src/userauth.o
npm ERR! LIBTOOL-STATIC Release/ssh2.a
npm ERR! CC(target) Release/obj.target/ntlmclient/vendor/libgit2/deps/ntlmclient/ntlm.o
npm ERR! CC(target) Release/obj.target/ntlmclient/vendor/libgit2/deps/ntlmclient/unicode_builtin.o
npm ERR! CC(target) Release/obj.target/ntlmclient/vendor/libgit2/deps/ntlmclient/util.o
npm ERR! CC(target) Release/obj.target/ntlmclient/vendor/libgit2/deps/ntlmclient/crypt_commoncrypto.o
npm ERR! LIBTOOL-STATIC Release/ntlmclient.a
npm ERR! CXX(target) Release/obj.target/nodegit/src/async_baton.o
npm ERR! Failed to execute '/usr/local/Cellar/node/16.11.1/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/@larscom/ng-chrome-extension/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/usr/local/lib/node_modules/@larscom/ng-chrome-extension/node_modules/nodegit/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp
npm ERR! info it worked if it ends with ok
npm ERR! node-pre-gyp info
npm ERR! using node-pre-gyp@0.13.0
npm ERR! node-pre-gyp info using node@16.11.1 | darwin | x64
npm ERR! node-pre-gyp WARN
npm ERR! Using request for node-pre-gyp https download
npm ERR! node-pre-gyp info
npm ERR! check checked for "/usr/local/lib/node_modules/@larscom/ng-chrome-extension/node_modules/nodegit/build/Release/nodegit.node" (not found)
npm ERR! node-pre-gyp
npm ERR! http GET https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v93-darwin-x64.tar.gz
npm ERR! node-pre-gyp
npm ERR! http 404 https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v93-darwin-x64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(404): https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v93-darwin-x64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not found for nodegit@0.27.0 and node@16.11.1 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp http 404 status code downloading tarball https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v93-darwin-x64.tar.gz
npm ERR! gyp
npm ERR! 
npm ERR! info it worked if it ends with ok
npm ERR! gyp info
npm ERR! using node-gyp@8.2.0
npm ERR! gyp info using node@16.11.1 | darwin | x64
npm ERR! gyp info
npm ERR! ok
npm ERR! gyp
npm ERR! info it worked if it ends with ok
npm ERR! gyp info
npm ERR! using node-gyp@8.2.0
npm ERR! gyp info using
npm ERR! node@16.11.1 | darwin | x64
npm ERR! gyp info
npm ERR! find Python using Python version 3.9.7 found at "/usr/local/opt/python@3.9/bin/python3.9"
npm ERR! gyp info spawn /usr/local/opt/python@3.9/bin/python3.9
npm ERR! gyp info
npm ERR! spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info
npm ERR! spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/@larscom/ng-chrome-extension/node_modules/nodegit/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp
npm ERR! info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/tim/Library/Caches/node-gyp/16.11.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/tim/Library/Caches/node-gyp/16.11.1',
npm ERR! gyp info
npm ERR! spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/tim/Library/Caches/node-gyp/16.11.1/<(target_arch)/node.lib',
npm ERR! gyp info
npm ERR! spawn args   '-Dmodule_root_dir=/usr/local/lib/node_modules/@larscom/ng-chrome-extension/node_modules/nodegit',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args
npm ERR! '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp
npm ERR! info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok
npm ERR! gyp
npm ERR! info it worked if it ends with ok
npm ERR! gyp info
npm ERR! using node-gyp@8.2.0
npm ERR! gyp info using node@16.11.1 | darwin | x64
npm ERR! gyp
npm ERR! info spawn make
npm ERR! gyp
npm ERR! info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/async_baton.cc:1:
npm ERR! In file included from ../src/../include/async_baton.h:5:
npm ERR! In file included from ../../nan/nan.h:58:
npm ERR! In file included from /Users/tim/Library/Caches/node-gyp/16.11.1/include/node/node.h:63:
npm ERR! In file included from /Users/tim/Library/Caches/node-gyp/16.11.1/include/node/v8.h:30:
npm ERR! /Users/tim/Library/Caches/node-gyp/16.11.1/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
npm ERR! !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                 ~~~~~^~~~~~~~~~~
npm ERR!                                      remove_cv
npm ERR! /Users/tim/Applications/Xcode_10.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:660:50: note: 'remove_cv' declared here
npm ERR! template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
npm ERR!                                                  ^
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/nodegit/src/async_baton.o] Error 1
npm ERR! gyp
npm ERR! ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp
npm ERR! ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 19.6.0
npm ERR! gyp ERR! command "/usr/local/Cellar/node/16.11.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/@larscom/ng-chrome-extension/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/usr/local/lib/node_modules/@larscom/ng-chrome-extension/node_modules/nodegit/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd
npm ERR! /usr/local/lib/node_modules/@larscom/ng-chrome-extension/node_modules/nodegit
npm ERR! gyp ERR! node -v v16.11.1
npm ERR! gyp ERR! node-gyp -v v8.2.0
npm ERR! gyp ERR!
npm ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/16.11.1/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/@larscom/ng-chrome-extension/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/usr/local/lib/node_modules/@larscom/ng-chrome-extension/node_modules/nodegit/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@larscom/ng-chrome-extension/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp
npm ERR! ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Darwin 19.6.0
npm ERR! node-pre-gyp ERR! command "/usr/local/Cellar/node/16.11.1/bin/node" "/usr/local/lib/node_modules/@larscom/ng-chrome-extension/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd
npm ERR! /usr/local/lib/node_modules/@larscom/ng-chrome-extension/node_modules/nodegit
npm ERR! node-pre-gyp ERR! node -v v16.11.1
npm ERR! node-pre-gyp ERR!
npm ERR! node-pre-gyp -v v0.13.0
npm ERR! node-pre-gyp ERR! not ok
npm ERR! [nodegit] ERROR - Could not finish install
npm ERR! [nodegit] ERROR - finished with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tim/.npm/_logs/2021-10-20T20_58_54_018Z-debug.log
```

**Comment by larscom** [comment]
I published a new version: **2.1.0**

That one should work with Node 14/16. 
Please re-open an issue if it doesn't work
